### ISSUE TITLE
Contao 4.9 - Captcha not working

### ISSUE THREAD

**Issue by Falkgeist** [loadbrain/rwcards-contao4#1]
When I try to preview or send the card in the frontend, putting the correct answer in the captcha widget, the form doesn't validate, asking to put the correct answer.

To be seen on [this page](https://contao4.glyc-germany.com/de/ecards.html)

**Comment by loadbrain** [comment]
Warum erscheint das Captcha überhaupt?
Hast Du das aktiviert?
Bei mir erscheint (https://loadbrain.weberr.de/rwcards.html) das nicht...

`Die Ressource von "https://contao4.glyc-germany.com/assets/mootools/mediabox//js/mediabox.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
ecards.html
Laden fehlgeschlagen für das <script> mit der Quelle "https://contao4.glyc-germany.com/assets/mootools/mediabox//js/mediabox.js". ecards.html:532:1
Uncaught TypeError: $$(...).mediabox is not a function`

Versuch das mal zu beheben, evtl. klappt es dann.

**Comment by Falkgeist** [comment]
Sorry, ich glaube ich war etwas voreilig. Es scheint noch ein altes Template in Verwendung zu sein, welches dieses Captcha noch einfügt. Ich nehme das erstmal raus und probiere es nochmal. Tut mir leid für den Aufwand.

**Comment by loadbrain** [comment]
Kein Problem, wenn das die Lösung ist umso besser... :smiley:
